# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JybKmw9oG4ngbToWkVVRF996MztBG72A
"""

# Data mentah yang berantakan dari supplier
data_supplier = [
    {"nama": "Kopi Susu", "harga": 15000, "stok": 20},
    {"nama": "", "harga": 0, "stok": 0},          # Data sampah (nama kosong)
    {"nama": "Teh Manis", "harga": 5000, "stok": 3},
    {"nama": "Susu Jahe", "harga": 12000, "stok": 2},
    {"nama": "Cokelat Panas", "harga": 0, "stok": 5} # Data sampah (harga 0)
]


# MEMBUAT FUNGSI (MESIN)
def bersihkan_data_barang(daftar_barang):
    data_valid = [] # Tempat menampung hasil yang bersih

    for barang in daftar_barang:
        # Syarat: Nama tidak boleh kosong DAN harga harus lebih dari 0
        if barang["nama"] != "" and barang["harga"] > 0:
            data_valid.append(barang)

    return data_valid

# MENGGUNAKAN FUNGSI
stok_siap_jual = bersihkan_data_barang(data_supplier)

# Menampilkan hasil
print("--- DAFTAR BARANG SIAP JUAL ---")
for item in stok_siap_jual:
    print(f"Produk: {item['nama']} | Harga: Rp{item['harga']} | Stok: {item['stok']}")

def sapa_pelanggan(nama_orang):
    # Di dalam sini adalah isi instruksi mesinnya
    print(f"Halo Kak {nama_orang}, selamat datang di toko cuan!")

    # Mari kita panggil mesinnya 3 kali dengan input berbeda
sapa_pelanggan("Budi")
sapa_pelanggan("Susi")
sapa_pelanggan("Eko")

def hitung_total(harga_barang):
    ongkir = 5000
    total = harga_barang + ongkir
    print(f"Harga Barang : Rp{harga_barang}")
    print(f"Total Bayar (+ongkir): Rp{total}")
    print("_" * 15) #tambahan garis

hitung_total(15000)
hitung_total(50000)
hitung_total(100000)

def cek_diskon(barang_diskon):
    diskon = 0.9
    harga_diskon = int(barang_diskon * diskon)
    print(f"Harga barang : Rp{barang_diskon}")
    print(f"Harga barang setelah diskon 10% : Rp{harga_diskon}")
    print("~" * 20)


cek_diskon(100000)
cek_diskon(235000)
cek_diskon(1570000)

# 1. Data Barang (List of Dictionaries)
stok_toko = [
    {"nama": "Sepatu", "harga": 200000},
    {"nama": "Baju", "harga": 100000},
    {"nama": "Topi", "harga": 50000}
]

# 2. Mesin Hitung Diskon (Fungsi yang kamu buat tadi)
def cetak_label_promo(produk):
    nama = produk["nama"]
    harga_asli = produk["harga"]
    harga_promo = int(harga_asli * 0.9)

    print(f"PROMO: {nama}")
    print(f"Harga Normal: Rp{harga_asli}")
    print(f"Harga Diskon: Rp{harga_promo}")
    print("-" * 15)

# 3. Eksekusi (Looping untuk semua barang)
print("=== DAFTAR HARGA PROMO HARI INI ===")
for barang in stok_toko:
    cetak_label_promo(barang)

def tambah_ongkir_return(harga):
    hasil = harga + 5000
    return hasil  # <--- Ini kuncinya!

# Sekarang kita bisa simpan hasilnya ke variabel (wadah)
total_belanja = tambah_ongkir_return(100000)

# Karena sudah disimpan, kita bisa olah lagi, misalnya dikali 2
bayar_dua_porsi = total_belanja * 2
print(f"Total untuk 2 orang: Rp{bayar_dua_porsi}")

def hitung_pajak(harga):
    pajak = harga * 0.1
    return pajak  # <--- Ini kuncinya!

# Sekarang kita bisa simpan hasilnya ke variabel (wadah)
pajak_saya = hitung_pajak(10000)

print(f"pajak yang harus saya bayar adalah: Rp{pajak_saya}")

def validasi_barang(nama, harga):
    # Jika nama kosong, kita kasih tau ini "Data Rusak"
    if nama == "" or harga <= 0:
        return "TIDAK VALID"
    else:
        return "SIAP JUAL"

# Simulasi cek barang dari supplier
status1 = validasi_barang("Kopi Hitam", 15000)
status2 = validasi_barang("", 0) # Barang rusak/data sampah

print(f"Barang 1: {status1}")
print(f"Barang 2: {status2}")

# 1. DATABASE MENU (Data kita)
menu_kopi = [
    {"produk": "Es Kopi Susu", "harga": 20000},
    {"produk": "Americano", "harga": 15000},
    {"produk": "Caramel Latte", "harga": 25000}
]

# 2. FUNGSI HITUNG PAJAK (Return Value)
def hitung_pajak(nominal):
    pajak = nominal * 0.1  # Pajak 10%
    return int(pajak)      # Mengembalikan hasil hitungan ke 'tangan' kita

# 3. PROSES KASIR (Looping & Logika)
print("=== STRUK PEMBAYARAN KASIR ===")
total_semua = 0

for item in menu_kopi:
    nama = item["produk"]
    harga = item["harga"]

    # Tambahkan harga ke keranjang belanja
    total_semua = total_semua + harga
    print(f"- {nama}: Rp{harga}")

# 4. MENGGUNAKAN HASIL RETURN
diskon = 5000
pajak_final = hitung_pajak(total_semua)
tagihan_akhir = total_semua + pajak_final - diskon

# 5. TAMPILKAN HASIL AKHIR
print("-" * 25)
print(f"Total Belanja : Rp{total_semua}")
print(f"Pajak (10%)   : Rp{pajak_final}")
print(f"Voucher diskon: Rp{diskon}")
print(f"TOTAL BAYAR   : Rp{tagihan_akhir}")
print("=== TERIMA KASIH ===")

nama_pelanggan = input("Masukkan nama pelanggan: ")
print(f"Halo {nama_pelanggan}, pesanan sedang disiapkan!")
harga = int(input("Masukkan harga barang: "))
total = harga + 5000 # Sekarang baru bisa dihitung!
print(f"jadi totalnya adalah : Rp{total}")

print("=== PROGRAM KASIR INTERAKTIF ===")

# 1. Kita minta input dari user
nama_barang = input("Nama Barang  : ")
harga_barang = int(input("Harga Barang : ")) # Diubah ke angka
jumlah_beli  = int(input("Jumlah Beli  : ")) # Diubah ke angka

# 2. Proses Hitung
total_belanja = harga_barang * jumlah_beli

# 3. Pakai fungsi pajak yang kita buat tadi
def hitung_pajak(nominal):
    return int(nominal * 0.1)

pajak = hitung_pajak(total_belanja)
total_akhir = total_belanja + pajak

# 4. Output Struk
print("\n" + "="*20)
print(f"Item  : {nama_barang}")
print(f"Total : Rp{total_belanja}")
print(f"Pajak : Rp{pajak}")
print(f"BAYAR : Rp{total_akhir}")
print("="*20)

# 1. Siapkan wadah kosong untuk menampung belanjaan
keranjang_belanja = []

print("=== KASIR TOKO CUAN JAYA ===")
print("(Ketik 'selesai' pada nama barang untuk menghitung total)\n")

while True:
    # 2. Minta input nama barang
    nama = input("Masukkan nama barang: ")

    # 3. Cek apakah user mau berhenti
    if nama.lower() == "selesai":
        break # Keluar dari perulangan

    # 4. Jika tidak berhenti, minta harga
    harga = int(input(f"Harga {nama}: "))

    # 5. Masukkan data ke dalam list 'keranjang_belanja' sebagai Dictionary
    barang_baru = {"produk": nama, "harga": harga}
    keranjang_belanja.append(barang_baru)
    print("Barang berhasil dicatat!\n")

# --- SETELAH SELESAI INPUT (OUTPUT STRUK) ---

print("\n" + "="*30)
print("       STRUK BELANJA")
print("="*30)

total_akhir = 0
for item in keranjang_belanja:
    print(f"{item['produk']:<15} : Rp{item['harga']}")
    total_akhir += item['harga'] # Sama dengan total_akhir = total_akhir + harga

print("-" * 30)
print(f"TOTAL BELANJA    : Rp{total_akhir}")
print("="*30)
print("Terima kasih sudah mampir!")

while True:
    nama = input("Masukkan nama barang: ")
    if nama.lower() == "selesai":
        break

    # --- MULAI ERROR HANDLING ---
    try:
        # Kita coba ubah input menjadi angka
        harga = int(input(f"Harga {nama}: "))
    except ValueError:
        # Kalau user ketik huruf, blok ini yang jalan
        print("❌ ERROR: Harga harus berupa ANGKA (tanpa titik/huruf)!")
        print("Silakan input ulang barang ini.\n")
        continue # Balik lagi ke awal loop (minta nama barang lagi)
    # --- SELESAI ERROR HANDLING ---

    barang_baru = {"produk": nama, "harga": harga}
    keranjang_belanja.append(barang_baru)
    print("✅ Barang berhasil dicatat!\n")

    # --- SETELAH SELESAI INPUT (OUTPUT STRUK) ---

print("\n" + "="*30)
print("       STRUK BELANJA")
print("="*30)

total_akhir = 0
for item in keranjang_belanja:
    print(f"{item['produk']:<15} : Rp{item['harga']}")
    total_akhir += item['harga'] # Sama dengan total_akhir = total_akhir + harga

print("-" * 30)
print(f"TOTAL BELANJA    : Rp{total_akhir}")
print("="*30)
print("Terima kasih sudah mampir!")

def hitung_patungan():
    print("=== KALKULATOR PATUNGAN CUAN ===")

    try:
        total_tagihan = int(input("Total tagihan (Rp): "))
        jumlah_orang = int(input("Dibagi berapa orang: "))

        hasil = total_tagihan / jumlah_orang
        print(f"\n✅ Masing-masing bayar: Rp{int(hasil)}")

    except ValueError:
        # Jika input berupa huruf/simbol
        print("❌ ERROR: Tolong masukkan angka yang bener dong, jangan huruf!")

    except ZeroDivisionError:
        # Jika jumlah orang diisi 0
        print("❌ ERROR: Mana bisa patungan tapi orangnya nol (0)?!")

    except Exception as e:
        # Pintu darurat untuk error lain yang tidak terduga
        print(f"❌ Terjadi kesalahan tak terduga: {e}")

# Panggil fungsinya
hitung_patungan()

# 1. Data hasil kasir kita (contoh sederhana)
nama_barang = "Kopi Susu"
total_bayar = 22000

# 2. PROSES MENYIMPAN KE FILE
# 'a' berarti 'Append' (menambah ke bawah, bukan menghapus yang lama)
with open("laporan_penjualan.txt", "a") as file:
    file.write(f"Barang: {nama_barang} | Total: Rp{total_bayar}\n")

print("✅ Transaksi berhasil dicatat ke laporan_penjualan.txt")

keranjang = [
    {"produk": "Kopi", "harga": 15000},
    {"produk": "Roti", "harga": 10000}
]
total = 25000

# KITA BUAT FILE STRUK
with open("struk_terakhir.txt", "w") as file: # 'w' untuk Overwrite/Tulis baru
    file.write("=== STRUK TOKO CUAN ===\n")
    for item in keranjang:
        file.write(f"{item['produk']} : Rp{item['harga']}\n")
    file.write("-" * 20 + "\n")
    file.write(f"TOTAL : Rp{total}\n")
    file.write("=======================\n")

print("📄 Struk belanja sudah dicetak ke file 'struk_terakhir.txt'!")

# 1. FUNGSI HITUNG (Mesin Otomatis)
def hitung_pajak(nominal):
    return int(nominal * 0.1)

# 2. MULAI PROGRAM
keranjang = []
print("=== SELAMAT DATANG DI KASIR CUAN JAYA ===")

while True:
    nama = input("\nMasukkan nama barang (atau ketik 'selesai'): ")

    if nama.lower() == "selesai":
        break

    # ERROR HANDLING UNTUK HARGA
    try:
        harga = int(input(f"Harga {nama}: "))
    except ValueError:
        print("❌ Masukkan angka saja! Ulangi input barang.")
        continue

    # SIMPAN KE KERANJANG
    barang = {"nama": nama, "harga": harga}
    keranjang.append(barang)
    print(f"✅ {nama} masuk keranjang.")

# 3. PROSES DATA & CETAK STRUK
if keranjang:
    total_belanja = 0

    # Membuka file untuk menyimpan struk
    with open("struk_belanja.txt", "w") as f:
        f.write("=== STRUK BELANJA TOKO CUAN ===\n")

        print("\n--- RINGKASAN BELANJA ---")
        for item in keranjang:
            line = f"{item['nama']:<15} : Rp{item['harga']}"
            print(line)
            f.write(line + "\n") # Tulis ke file
            total_belanja += item['harga']

        pajak = hitung_pajak(total_belanja)
        total_akhir = total_belanja + pajak

        # Penutup Struk
        footer = f"\nTotal Belanja : Rp{total_belanja}\nPajak (10%)   : Rp{pajak}\nTOTAL AKHIR   : Rp{total_akhir}\n"
        footer += "===============================\nTerima Kasih!"

        print("-" * 25)
        print(footer)
        f.write("-" * 25 + footer) # Simpan semua ke file

    print("\n📄 Struk telah tersimpan di 'struk_belanja.txt'")
else:
    print("\nKeranjang kosong. Tidak ada transaksi.")

harga_kursus = 500000
diskon_member = 100000

# 1. Minta input potongan berkah dari user
potongan_berkah = int(input("Masukkan nominal Potongan Cuan Berkah: "))

# 2. Hitung total sementara
total = harga_kursus - diskon_member - potongan_berkah

# --- TANTANGAN: TULIS LOGIKA "PAGAR NOL" DI SINI ---
if total < 0 : # Isi bagian ini
    total = 0  # Isi bagian ini
# --------------------------------------------------

print(f"Total yang harus dibayar: Rp{total}")

import pandas as pd # Kita panggil Pandas dengan nama alias 'pd'
import numpy as np

# 1. Data kita (List of Dictionaries yang sudah kamu kuasai)
data_keranjang = [
    {"Barang": "Kopi Susu", "Harga": 20000, "Kategori": "Minuman"},
    {"Barang": "Roti Bakar", "Harga": 15000, "Kategori": "Makanan"},
    {"Barang": "Americano", "Harga": 18000, "Kategori": "Minuman"}
]

# 2. Masukkan data ke "Mesin Pandas" (DataFrame)
df = pd.DataFrame(data_keranjang)

# 3. ANALISIS DATA SEDERHANA (Sisi Analis-nya di sini!)
df["status"] = np.where(df["Harga"] < 17000, "MURAH", "MAHAL")
total_pendapatan = df["Harga"].sum()
rata_rata_harga = df["Harga"].mean()

print("--- HASIL ANALISIS SINGKAT ---")
print(df) # Menampilkan tabel di layar
print(f"\nTotal Omzet: Rp{total_pendapatan}")
print(f"Rata-rata Harga: Rp{int(rata_rata_harga)}")

# 4. SIMPAN KE EXCEL (Cuan Moment!)
df.to_excel("Laporan_Penjualan.xlsx", index=False)

print("\n✅ File 'Laporan_Penjualan.xlsx' sudah siap dikirim ke bos!")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Ambil Data
df = pd.read_csv('sample_data/california_housing_train.csv')

# 2. Buat Ringkasan Statistik (Mantra .describe)
# Kita mau tahu rata-rata harga, harga termurah, dan termahal
ringkasan_statistik = df[['median_house_value', 'housing_median_age', 'total_rooms']].describe()

# 3. OTOMASI: Simpan semuanya ke satu file Excel 'Dashboard_Final.xlsx'
with pd.ExcelWriter('Dashboard_Final.xlsx') as writer:
    # Halaman 1: Ringkasan Angka Penting
    ringkasan_statistik.to_excel(writer, sheet_name='Ringkasan_Bos')
    # Halaman 2: Data Lengkap (Hanya 100 baris biar tidak keberatan)
    df.head(100).to_excel(writer, sheet_name='Data_Mentah', index=False)

# 4. Buat Grafik Perbandingan Harga
plt.figure(figsize=(8, 5))
sns.boxplot(x=df['housing_median_age'] > 30, y=df['median_house_value'], palette='coolwarm')
plt.title('Perbandingan Harga: Rumah Tua vs Rumah Muda')
plt.xticks([0, 1], ['Rumah Muda', 'Rumah Tua'])
plt.savefig('Grafik_Final.png', dpi=300)
plt.show()

print("🏁 SEMUA SIHIR SELESAI!")
print("Cek folder kiri (📂), download 'Dashboard_Final.xlsx' dan 'Grafik_Final.png'.")

import pandas as pd

# Membuat data sederhana: Nama Barang, Harga, dan Stok
data = {
    'Nama_Barang': ['Kopi', 'Teh', 'Susu', 'Gula', 'Cokelat'],
    'Harga': [15000, 10000, 20000, 12000, 25000],
    'Stok': [50, 100, 30, 80, 20]
}

df_awal = pd.DataFrame(data)

# Menyimpan menjadi file Excel di folder Colab
df_awal.to_excel('data_praktek.xlsx', index=False)
print("✅ File 'data_praktek.xlsx' berhasil dibuat di folder kiri (📂)!")

# Membaca kembali file Excel yang tadi dibuat
df_masuk = pd.read_excel('data_praktek.xlsx')

# Menampilkan data yang berhasil dimasukkan
print("--- Data yang Berhasil Dimasukkan ---")
display(df_masuk)

# Menambah kolom baru: Total Nilai
df_masuk['Total_Nilai'] = df_masuk['Harga'] * df_masuk['Stok']

# Mencari barang dengan nilai stok tertinggi
barang_termahal = df_masuk.sort_values(by='Total_Nilai', ascending=False)
display(barang_termahal)

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Atur ukuran gambar agar pas di mata
plt.figure(figsize=(10, 6))

# 2. Buat Grafik Batang: Nama Barang vs Total Nilai Stok
# Kita urutkan datanya dulu agar grafiknya rapi dari yang tertinggi
data_urut = df_masuk.sort_values('Total_Nilai', ascending=False)

sns.barplot(data=data_urut, x='Nama_Barang', y='Total_Nilai', palette='viridis')

# 3. Tambahkan "Bumbu" Informasi
plt.title('Total Nilai Aset per Barang di Gudang', fontsize=15, pad=20)
plt.xlabel('Nama Produk', fontsize=12)
plt.ylabel('Total Nilai (Rp)', fontsize=12)

# 4. Simpan hasilnya jadi gambar (untuk laporan)
plt.savefig('visualisasi_aset.png', dpi=300, bbox_inches='tight')

# 5. Tampilkan!
plt.show()

# Menambah data baru "Bantal Pijat"
data_baru = {
    'Nama_Barang': ['Kopi', 'Teh', 'Susu', 'Gula', 'Cokelat', 'Bantal Pijat'],
    'Harga': [15000, 10000, 20000, 12000, 25000, 150000], # Bantal pijat harganya 150rb
    'Stok': [50, 100, 30, 80, 20, 15] # Stoknya ada 15 biji
}

df_lengkap = pd.DataFrame(data_baru)
df_lengkap['Total_Nilai'] = df_lengkap['Harga'] * df_lengkap['Stok']

# Tampilkan datanya
df_lengkap

from matplotlib.backends.backend_pdf import PdfPages

# 1. Siapkan Nama File PDF-nya
nama_pdf = "Laporan_Aset_Gudang.pdf"

with PdfPages(nama_pdf) as pdf:
    # --- HALAMAN 1: GRAFIK BATANG ---
    plt.figure(figsize=(10, 6))
    sns.barplot(data=df_lengkap.sort_values('Total_Nilai', ascending=False),
                x='Nama_Barang', y='Total_Nilai', palette='magma')
    plt.title('Distribusi Nilai Aset (Termasuk Bantal Pijat)', fontsize=14)
    plt.xticks(rotation=45) # Biar tulisan Nama Barang tidak tabrakan
    pdf.savefig()  # Simpan halaman pertama
    plt.close()

    # --- HALAMAN 2: TABEL DATA ---
    # Kita buat tabel bersih di dalam PDF
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.axis('tight')
    ax.axis('off')
    tabel = ax.table(cellText=df_lengkap.values, colLabels=df_lengkap.columns, loc='center', cellLoc='center')
    tabel.auto_set_font_size(False)
    tabel.set_fontsize(10)
    plt.title('Tabel Rincian Stok Barang', pad=20)
    pdf.savefig() # Simpan halaman kedua
    plt.close()

print(f"✅ SULAP BERHASIL! File '{nama_pdf}' sudah ada di folder kiri (📂).")

import matplotlib.pyplot as plt

# 1. Siapkan data (kita pakai Total_Nilai agar persentasenya akurat)
label_barang = df_lengkap['Nama_Barang']
nilai_aset = df_lengkap['Total_Nilai']

# 2. Atur Ukuran Gambar
plt.figure(figsize=(10, 8))

# 3. Buat Pie Chart
# 'autopct' fungsinya untuk memunculkan angka persen otomatis
# 'explode' fungsinya untuk sedikit menarik "potongan" agar menonjol
potongan_menonjol = [0, 0, 0, 0, 0, 0.1] # Kita buat Bantal Pijat (index terakhir) agak keluar

plt.pie(nilai_aset, labels=label_barang, autopct='%1.1f%%',
        startangle=140, colors=sns.color_palette('pastel'),
        explode=potongan_menonjol, shadow=True)

# 4. Tambahkan Judul
plt.title('Persentase Kontribusi Aset per Barang', fontsize=15)

# 5. Simpan & Tampilkan
plt.savefig('persentase_aset.png', dpi=300)
plt.show()

# 1. Mengurutkan data dari yang TERMAHAL ke termurah
df_urut = df_lengkap.sort_values(by='Total_Nilai', ascending=False)

# 2. Hanya ambil 3 BESAR (Top 3)
top_3_aset = df_urut.head(3)

# 3. Ganti Nama Kolom agar lebih keren untuk laporan
top_3_aset = top_3_aset.rename(columns={
    'Nama_Barang': 'Produk_Unggulan',
    'Total_Nilai': 'Nilai_Investasi_Rp'
})

print("--- 3 Aset Terbesar Kita ---")
display(top_3_aset)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

def sihir_laporan_otomatis(df_sumber, nama_file_pdf):
    # 1. PROSES DATA: Hitung Total Nilai Aset
    df = df_sumber.copy()
    df['Total_Nilai'] = df['Harga'] * df['Stok']
    df_urut = df.sort_values('Total_Nilai', ascending=False)

    # 2. MULAI MENCETAK KE PDF
    with PdfPages(nama_file_pdf) as pdf:

        # --- HALAMAN 1: BAR CHART (Perbandingan Harga) ---
        plt.figure(figsize=(10, 6))
        sns.barplot(data=df_urut, x='Nama_Barang', y='Total_Nilai', palette='magma')
        plt.title('Peringkat Aset Gudang (Berdasarkan Nilai Rupiah)', fontsize=14)
        plt.xticks(rotation=45)
        pdf.savefig() # Simpan ke PDF
        plt.show() # Tampilkan di layar
        plt.close()

        # --- HALAMAN 2: PIE CHART (Persentase Kontribusi) ---
        plt.figure(figsize=(8, 8))
        plt.pie(df['Total_Nilai'], labels=df['Nama_Barang'], autopct='%1.1f%%',
                startangle=140, colors=sns.color_palette('viridis'))
        plt.title('Komposisi Persentase Stok di Gudang', fontsize=14)
        pdf.savefig()
        plt.show()
        plt.close()

        # --- HALAMAN 3: TABEL RINGKASAN ---
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.axis('tight')
        ax.axis('off')
        tabel = ax.table(cellText=df_urut.values, colLabels=df_urut.columns, loc='center', cellLoc='center')
        tabel.auto_set_font_size(False)
        tabel.set_fontsize(10)
        plt.title('Laporan Tabel Detail Stok Terupdate', pad=20)
        pdf.savefig()
        plt.close()

    print(f"✨ SIHIR BERHASIL! File '{nama_file_pdf}' sudah siap di folder kiri (📂).")

# --- CARA PAKAINYA SANGAT MUDAH ---
# Cukup panggil fungsinya dengan data yang kamu punya
sihir_laporan_otomatis(df_lengkap, 'Laporan_Otomatis_Sesi_Ini.pdf')

# 1. Simpan Data Lama untuk Perbandingan
total_lama = df_lengkap['Total_Nilai'].sum()

# 2. UPDATE: Ubah harga Bantal Pijat (asumsi index-nya adalah 5)
# Kita pakai .at[baris, kolom] untuk mengubah 1 kotak saja
df_update = df_lengkap.copy()
df_update.at[5, 'Harga'] = 100000

# 3. Hitung Ulang Total Nilai yang Baru
df_update['Total_Nilai'] = df_update['Harga'] * df_update['Stok']
total_baru = df_update['Total_Nilai'].sum()

# 4. HITUNG SELISIH
selisih = total_lama - total_baru

print(f"💰 Total Nilai Aset Lama: Rp{total_lama:,}")
print(f"📉 Total Nilai Aset Baru: Rp{total_baru:,}")
print(f"⚠️ SELISIH PENURUNAN: Rp{selisih:,}")

# Tampilkan Tabel Perubahan
display(df_update)

# Panggil template otomatis untuk data yang sudah di-update harganya
sihir_laporan_otomatis(df_update, 'Laporan_Setelah_Diskon.pdf')

import pandas as pd

# 1. Kita buat data yang "Kotor" (Ada yang kosong dan dobel)
data_kotor = {
    'Nama_Barang': ['Kopi', 'Teh', None, 'Kopi', 'Bantal Pijat', 'bantal pijat'],
    'Harga': [15000, 10000, 20000, 15000, 100000, 100000],
    'Stok': [50, 100, None, 50, 15, 15]
}
df_kotor = pd.DataFrame(data_kotor)

print("--- Data Sebelum Dicuci (Kotor) ---")
display(df_kotor)

# 2. PROSES PENCUCIAN
# A. Buang baris yang ada kosongnya (NaN)
df_bersih = df_kotor.dropna()

# B. Samakan semua tulisan jadi Huruf Besar agar tidak dobel karena beda huruf
df_bersih['Nama_Barang'] = df_bersih['Nama_Barang'].str.upper()

# C. Buang data yang duplikat/sama persis
df_bersih = df_bersih.drop_duplicates()

print("\n--- Data Setelah Dicuci (Kinclong) ---")
display(df_bersih)

import pandas as pd

# Data Januari
jan = pd.DataFrame({'Barang': ['Kopi', 'Teh'], 'Terjual': [20, 15]})
# Data Februari
feb = pd.DataFrame({'Barang': ['Susu', 'Cokelat'], 'Terjual': [10, 25]})

# MANTRA: Gabungkan ke bawah
laporan_dua_bulan = pd.concat([jan, feb], ignore_index=True)

print("--- Laporan Gabungan Januari + Februari ---")
display(laporan_dua_bulan)

# Tabel Harga
df_harga = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Teh', 'Susu'],
    'Harga_Satuan': [15000, 10000, 20000]
})

# Tabel Penjualan
df_laku = pd.DataFrame({
    'Nama_Barang': ['Susu', 'Kopi'],
    'Jumlah_Laku': [5, 12]
})

# MANTRA: Gabungkan menyamping berdasarkan 'Nama_Barang'
# 'how=left' artinya kita fokus pada semua barang yang ada di daftar harga
hasil_akhir = pd.merge(df_harga, df_laku, on='Nama_Barang', how='left')

# Isi kolom yang kosong (NaN) dengan angka 0 (artinya tidak ada yang laku)
hasil_akhir['Jumlah_Laku'] = hasil_akhir['Jumlah_Laku'].fillna(0)

print("--- Hasil Gabungan Harga & Penjualan ---")
display(hasil_akhir)

import pandas as pd

# 1. DATA MASTER: Daftar harga semua barang
df_produk = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Teh', 'Susu', 'Bantal Pijat'],
    'Harga': [15000, 10000, 20000, 100000]
})

# 2. DATA TRANSAKSI: Penjualan hari ini
df_transaksi = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Bantal Pijat', 'Susu'],
    'Qty': [5, 2, 3] # Kopi laku 5, Bantal 2, Susu 3
})

# 3. MANTRA MERGE (Left Join)
# 'how=left' artinya: Pertahankan SEMUA barang di df_produk,
# tempelkan data transaksi jika ketemu kecocokan.
df_laporan = pd.merge(df_produk, df_transaksi, on='Nama_Barang', how='left')

# 4. PEMBERSIHAN: Ubah yang kosong (NaN) menjadi 0 (karena tidak laku)
df_laporan['Qty'] = df_laporan['Qty'].fillna(0)

print("--- Hasil Gabungan (VLOOKUP Ala Python) ---")
display(df_laporan)

import pandas as pd

# 1. TABEL STOK (Data Master kita)
df_stok = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Teh', 'Susu', 'Bantal Pijat'],
    'Harga': [15000, 10000, 20000, 100000],
    'Stok_Awal': [50, 100, 30, 15]
})

# 2. TABEL PENJUALAN (Catatan Kasir hari ini)
# Ceritanya Bantal Pijat belum laku, jadi tidak ada di daftar ini
df_penjualan = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Susu', 'Teh', 'Bantal Pijat'],
    'Jumlah_Terjual': [10, 5, 20, 10]
})

# 3. MANTRA GABUNG (Merge)
# Kita gabungkan data stok dengan data penjualan
df_gabung = pd.merge(df_stok, df_penjualan, on='Nama_Barang', how='left')

# 4. MEMBERSIHKAN DATA (Isi yang kosong/NaN dengan 0)
df_gabung['Jumlah_Terjual'] = df_gabung['Jumlah_Terjual'].fillna(0)

# 5. HITUNG SISA & PENDAPATAN
df_gabung['Sisa_Stok'] = df_gabung['Stok_Awal'] - df_gabung['Jumlah_Terjual']
df_gabung['Total_Pendapatan'] = df_gabung['Jumlah_Terjual'] * df_gabung['Harga']

print("--- LAPORAN GABUNGAN STOK & PENJUALAN ---")
display(df_gabung)

# Hitung Total Uang Masuk Hari Ini
total_uang = df_gabung['Total_Pendapatan'].sum()
print(f"\n💰 TOTAL UANG DI KASIR: Rp{total_uang:,}")

import pandas as pd

# 1. Gunakan data gabungan kita yang tadi
# (Pastikan kamu sudah menjalankan kode 'df_gabung' sebelumnya)

# 2. FUNGSI SIHIR: Aturan Warna
def warnai_stok_kritis(nilai):
    # Jika stok di bawah 10, kasih latar belakang merah
    if nilai < 10:
        return 'background-color: #ffcccc; color: #cc0000; font-weight: bold'
    # Jika stok aman, biarkan polos atau kasih warna hijau muda
    else:
        return 'background-color: #e6ffed; color: #006622'

# 3. TERAPKAN SIHIRNYA
# Kita fokuskan hanya pada kolom 'Sisa_Stok'
tampilan_keren = df_gabung.style.applymap(warnai_stok_kritis, subset=['Sisa_Stok'])

print("--- LAPORAN DENGAN HIGHLIGHT OTOMATIS ---")
display(tampilan_keren)


# Memberi warna kuning pada nilai tertinggi di kolom Pendapatan
tampilan_juara = df_gabung.style.highlight_max(subset=['Total_Pendapatan'], color='yellow')

print("\n")
display(tampilan_juara)

# 1. Pastikan library openpyxl terpasang (Biasanya sudah ada di Colab)
# 2. Definisikan aturan warna (Sama seperti tadi)
def gaya_stok(stok):
    if stok < 10:
        return 'background-color: #ffcccc' # Merah Muda untuk stok kritis
    else:
        return 'background-color: #e6ffed' # Hijau Muda untuk stok aman

# 3. TERAPKAN GAYA PADA DATAFRAME
df_berwarna = df_gabung.style.applymap(gaya_stok, subset=['Sisa_Stok'])

# 4. SIMPAN KE EXCEL (Ini intinya!)
# Kita gunakan engine='openpyxl' agar format warnanya ikut terbawa
df_berwarna.to_excel('Laporan_Stok_Berwarna.xlsx', engine='openpyxl', index=False)

print("✅ SIHIR PERMANEN BERHASIL!")
print("Cek folder kiri (📂), download 'Laporan_Stok_Berwarna.xlsx', dan buka di Excel laptopmu.")

# 1. Pastikan mesin pembaca/penulis Excel terbaru sudah terpasang
!pip install openpyxl xlsxwriter -q

import pandas as pd

# 2. Definisikan gaya (Warna Latar & Warna Tulisan)
def gaya_stok_permanen(stok):
    if stok < 10:
        # Merah untuk stok sedikit
        return 'background-color: red; color: white; font-weight: bold'
    else:
        # Hijau untuk stok aman
        return 'background-color: green; color: white'

# 3. Buat file Excel dengan 'Mesin' XlsxWriter (Ini paling jago soal warna)
nama_file = 'Laporan_Stok_Berwarna_V2.xlsx'

# Terapkan gaya dan simpan
with pd.ExcelWriter(nama_file, engine='xlsxwriter') as writer:
    df_gabung.style.applymap(gaya_stok_permanen, subset=['Sisa_Stok']).to_excel(writer, index=False, sheet_name='Laporan')

print(f"✅ MESIN DIPERBARUI! Silakan download '{nama_file}' di folder kiri.")

import pandas as pd

# 1. DATA MASTER (Harga Beli vs Harga Jual)
df_profit = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Teh', 'Susu', 'Bantal Pijat'],
    'Harga_Beli': [8000, 5000, 12000, 70000],  # Modal per unit
    'Harga_Jual': [15000, 10000, 20000, 100000], # Harga ke konsumen
    'Terjual': [10, 20, 5, 2] # Jumlah yang laku
})

# 2. HITUNG LABA KOTOR PER BARANG
# Laba Kotor = (Harga Jual - Harga Beli) * Jumlah Terjual
df_profit['Laba_Kotor'] = (df_profit['Harga_Jual'] - df_profit['Harga_Beli']) * df_profit['Terjual']

# 3. HITUNG TOTAL & BIAYA LAIN-LAIN
total_laba_kotor = df_profit['Laba_Kotor'].sum()
biaya_operasional = 50000  # Misal: Biaya packing & kuota internet
pajak_persen = 10 / 100    # Pajak 10%

# 4. HITUNG LABA BERSIH
total_pajak = total_laba_kotor * pajak_persen
laba_bersih = total_laba_kotor - biaya_operasional - total_pajak

print("--- RINCIAN PROFIT PER BARANG ---")
display(df_profit)

print("-" * 35)
print(f"💰 Total Laba Kotor    : Rp{total_laba_kotor:,}")
print(f"📦 Biaya Operasional   : Rp{biaya_operasional:,}")
print(f"💸 Pajak (10%)         : Rp{total_pajak:,.0f}")
print(f"🏆 LABA BERSIH (NET)   : Rp{laba_bersih:,.0f}")

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

# 1. Siapkan data untuk grafik
# Kita hitung Total Modal per barang
df_profit['Total_Modal'] = df_profit['Harga_Beli'] * df_profit['Terjual']

# 2. Kita ubah bentuk data agar mudah dibaca oleh Seaborn (Melting)
df_plot = df_profit.melt(id_vars='Nama_Barang',
                         value_vars=['Total_Modal', 'Laba_Kotor'],
                         var_name='Kategori', value_name='Rupiah')

# 3. Mulai Menggambar
plt.figure(figsize=(12, 6))
sns.barplot(data=df_plot, x='Nama_Barang', y='Rupiah', hue='Kategori', palette='viridis')

# 4. Tambahkan Detail Perhiasan Grafik
plt.title('Perbandingan Total Modal vs Laba Kotor per Barang', fontsize=15)
plt.ylabel('Nilai (Rp)')
plt.xlabel('Nama Produk')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Tampilkan
plt.show()

# 1. Cari Produk dengan Laba Tertinggi
produk_juara = df_profit.loc[df_profit['Laba_Kotor'].idxmax(), 'Nama_Barang']
nilai_juara = df_profit['Laba_Kotor'].max()

# 2. Hitung Margin Keuntungan Rata-rata (%)
df_profit['Margin_%'] = (df_profit['Laba_Kotor'] / (df_profit['Harga_Beli'] * df_profit['Terjual'])) * 100
margin_rata2 = df_profit['Margin_%'].mean()

# 3. MANTRA KESIMPULAN (Auto-Text)
kesimpulan = f"""
📢 --- RINGKASAN EKSEKUTIF ---
✅ Produk Paling Cuan: {produk_juara} (Untung Rp{nilai_juara:,})
📈 Rata-rata Margin Keuntungan: {margin_rata2:.1f}%
💰 Estimasi Laba Bersih Setelah Pajak: Rp{laba_bersih:,.0f}
"""

# 4. Tampilkan Hasilnya
print(kesimpulan)

# Tips Pro: Jika Laba Bersih di bawah 100rb, beri peringatan!
if laba_bersih < 100000:
    print("⚠️ PERINGATAN: Laba bersih tipis! Coba kurangi biaya operasional.")
else:
    print("🚀 PERFORMA BAGUS: Bisnis berjalan sehat hari ini!")

import pandas as pd
import numpy as np
# Pastikan ejaannya benar: xlsxwriter (tanpa huruf 't' di tengah)
!pip install xlsxwriter -q

import xlsxwriter
print("✅ Mesin XlsxWriter siap tempur!")

# 1. PERSIAPAN DATA (Stok & Penjualan)
df_stok = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Teh', 'Susu', 'Bantal Pijat'],
    'Harga_Beli': [8000, 5000, 12000, 70000],
    'Harga_Jual': [15000, 10000, 20000, 100000],
    'Stok_Awal': [50, 100, 30, 15]
})

df_penjualan = pd.DataFrame({
    'Nama_Barang': ['Kopi', 'Susu', 'Teh'],
    'Terjual': [10, 5, 20]
})

# 2. PROSES GABUNG & HITUNG PROFIT
df_final = pd.merge(df_stok, df_penjualan, on='Nama_Barang', how='left').fillna(0)
df_final['Sisa_Stok'] = df_final['Stok_Awal'] - df_final['Terjual']
df_final['Laba_Kotor'] = (df_final['Harga_Jual'] - df_final['Harga_Beli']) * df_final['Terjual']

# 3. LOGIKA KESIMPULAN OTOMATIS
produk_juara = df_final.loc[df_final['Laba_Kotor'].idxmax(), 'Nama_Barang']
total_laba = df_final['Laba_Kotor'].sum()
pesan_bisnis = "🚀 PERFORMA BAGUS!" if total_laba > 100000 else "⚠️ PERINGATAN: Laba Tipis!"

# 4. SIHIR PEWARNAAN (Highlight)
def gaya_laporan(row):
    # Warna Merah untuk stok kritis (< 10)
    warna_stok = 'background-color: #ffcccc' if row['Sisa_Stok'] < 10 else ''
    # Warna Emas untuk produk paling cuan
    warna_cuan = 'background-color: #fff2cc' if row['Nama_Barang'] == produk_juara else ''
    return [warna_stok if col == 'Sisa_Stok' else (warna_cuan if col == 'Laba_Kotor' else '') for col in row.index]

# 5. SIMPAN KE EXCEL DENGAN ENGINE XLSXWRITER
with pd.ExcelWriter('Laporan_Bisnis_Final.xlsx', engine='xlsxwriter') as writer:
    # Terapkan Gaya & Simpan Tabel Utama
    df_final.style.apply(gaya_laporan, axis=1).to_excel(writer, index=False, sheet_name='Ringkasan')

    # Tambahkan Teks Kesimpulan di bawah Tabel (Baris ke-8)
    workbook  = writer.book
    worksheet = writer.sheets['Ringkasan']
    format_bold = workbook.add_format({'bold': True, 'font_color': 'blue', 'font_size': 12})

    worksheet.write('A8', '--- RINGKASAN EKSEKUTIF ---', format_bold)
    worksheet.write('A9', f'🏆 Produk Terlaris: {produk_juara}')
    worksheet.write('A10', f'💰 Total Laba Kotor: Rp{total_laba:,}')
    worksheet.write('A11', f'Status Bisnis: {pesan_bisnis}')

print("✨ SEMUA JURUS TELAH DIBUNGKUS!")
print("Cek folder 📂, download 'Laporan_Bisnis_Final.xlsx', dan pamerkan hasilnya!")

"""
PROJECT: Automated Retail Business Intelligence (ARBI)
AUTHOR: M Hafidh Muzakki
DESCRIPTION:
Sistem ini mengotomatiskan pengolahan data stok dan penjualan,
membersihkan data kotor, menghitung profit bersih, serta
menghasilkan laporan Excel berwarna dengan kesimpulan otomatis.
"""

import pandas as pd
import numpy as np

# --- STAGE 1: DATA INGESTION (Simulasi data dari Excel/CSV) ---
def load_data():
    # Data Master Produk
    df_stok = pd.DataFrame({
        'ID_Produk': ['P001', 'P002', 'P003', 'P004'],
        'Nama_Barang': ['Kopi Gayo', 'Teh Melati', 'Susu Murni', 'Bantal Pijat'],
        'Modal_Per_Unit': [8000, 5000, 12000, 70000],
        'Harga_Jual': [15000, 10000, 20000, 100000],
        'Stok_Gudang': [50, 100, 30, 15]
    })

    # Data Penjualan Harian
    df_transaksi = pd.DataFrame({
        'Nama_Barang': ['Kopi Gayo', 'Susu Murni', 'Teh Melati'],
        'Qty_Terjual': [10, 5, 20]
    })
    return df_stok, df_transaksi

# --- STAGE 2: DATA PROCESSING & CALCULATION ---
def process_report(df_stok, df_transaksi):
    # Merge data stok dan transaksi (VLOOKUP ala Python)
    report = pd.merge(df_stok, df_transaksi, on='Nama_Barang', how='left').fillna(0)

    # Kalkulasi Bisnis
    report['Total_Modal'] = report['Modal_Per_Unit'] * report['Qty_Terjual']
    report['Total_Omzet'] = report['Harga_Jual'] * report['Qty_Terjual']
    report['Laba_Kotor'] = report['Total_Omzet'] - report['Total_Modal']
    report['Sisa_Stok'] = report['Stok_Gudang'] - report['Qty_Terjual']

    return report

# --- STAGE 3: AUTOMATED INSIGHTS ---
def get_summary(report):
    top_product = report.loc[report['Laba_Kotor'].idxmax(), 'Nama_Barang']
    total_profit = report['Laba_Kotor'].sum()
    low_stock_count = len(report[report['Sisa_Stok'] < 10])

    return f"""
    === EXECUTIVE SUMMARY ===
    🥇 Produk Profit Tertinggi : {top_product}
    💰 Total Laba Kotor        : Rp{total_profit:,}
    ⚠️ Barang Perlu Restock    : {low_stock_count} Item
    """

# --- STAGE 4: EXPORT TO EXCEL WITH STYLING ---
def export_excel(report, summary_text):
    !pip install xlsxwriter -q
    with pd.ExcelWriter('Portfolio_Retail_Report.xlsx', engine='xlsxwriter') as writer:
        # Styling baris berdasarkan logika bisnis
        def apply_styles(row):
            styles = [''] * len(row)
            if row['Sisa_Stok'] < 10:
                styles[row.index.get_loc('Sisa_Stok')] = 'background-color: #ffcccc'
            if row['Laba_Kotor'] == report['Laba_Kotor'].max():
                styles[row.index.get_loc('Laba_Kotor')] = 'background-color: #fff2cc'
            return styles

        report.style.apply(apply_styles, axis=1).to_excel(writer, index=False, sheet_name='Dashboard')

        # Menambahkan summary ke file Excel
        worksheet = writer.sheets['Dashboard']
        worksheet.write('A10', summary_text)

# RUNNING THE PROJECT
stok, transaksi = load_data()
final_report = process_report(stok, transaksi)
executive_summary = get_summary(final_report)

print(executive_summary)
export_excel(final_report, executive_summary)
print("✅ Proyek Portofolio 1 Berhasil Dibuat!")